### ISSUE TITLE
create a new file favorite-foods.txt

### ISSUE THREAD

**Issue by drewpatrickboyle** [CSCI-3030-GroupGitAssignment/our-favorites#1]
(15 minutes) Assign the role of maintainer to one of your team members, and the role of contributor to another. Your team's goal is to have the contributor create a new file favorite-foods.txt in the root of the project containing a couple of their favorite foods. Follow the Contribution Workflow to accomplish this goal. Maintainer, when asked to review the PR, accept and merge the PR.

Contribution Workflow

**Comment by wayfarer1549** [comment]
This issue has been successfully implemented and merged.
